export const KERALA_DISTRICTS = [
  'High Court of Kerala',
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasaragod',
  'Kollam',
  'Kottayam',
  'Kozhikode',
  'Malappuram',
  'Palakkad',
  'Pathanamthitta',
  'Thiruvananthapuram',
  'Thrissur',
  'Wayanad',
  'Other'
];

export const COURTS_BY_DISTRICT: Record<string, string[]> = {
  'High Court of Kerala': [
    'High Court of Kerala — Original Side',
    'High Court of Kerala — Appellate Side',
    'High Court of Kerala — Writ Jurisdiction',
  ],
  'Thiruvananthapuram': [
    'High Court of Kerala',
    'District Court, Thiruvananthapuram',
    'Sub Court, Thiruvananthapuram',
    'Munsiff Court, Thiruvananthapuram',
    'Family Court, Thiruvananthapuram',
    'Chief Judicial Magistrate Court, Thiruvananthapuram',
    'Judicial First Class Magistrate Court, Thiruvananthapuram',
    'Sessions Court, Thiruvananthapuram',
    'MACT, Thiruvananthapuram',
    'Consumer Disputes Redressal Commission, Thiruvananthapuram',
    'Rent Control Court, Thiruvananthapuram',
    'Labour Court, Thiruvananthapuram',
    'Industrial Tribunal, Thiruvananthapuram',
  ],
  'Ernakulam': [
    'High Court of Kerala',
    'District Court, Ernakulam',
    'Sub Court, Ernakulam',
    'Munsiff Court, Ernakulam',
    'Family Court, Ernakulam',
    'Chief Judicial Magistrate Court, Ernakulam',
    'Judicial First Class Magistrate Court, Ernakulam',
    'Sessions Court, Ernakulam',
    'MACT, Ernakulam',
    'Consumer Disputes Redressal Commission, Ernakulam',
    'Rent Control Court, Ernakulam',
    'Labour Court, Ernakulam',
    'Commercial Court, Ernakulam',
  ],
  'Thrissur': [
    'District Court, Thrissur',
    'Sub Court, Thrissur',
    'Munsiff Court, Thrissur',
    'Family Court, Thrissur',
    'Chief Judicial Magistrate Court, Thrissur',
    'Judicial First Class Magistrate Court, Thrissur',
    'Sessions Court, Thrissur',
    'MACT, Thrissur',
    'Consumer Disputes Redressal Commission, Thrissur',
    'Rent Control Court, Thrissur',
    'Labour Court, Thrissur',
  ],
  'Kozhikode': [
    'District Court, Kozhikode',
    'Sub Court, Kozhikode',
    'Munsiff Court, Kozhikode',
    'Family Court, Kozhikode',
    'Chief Judicial Magistrate Court, Kozhikode',
    'Judicial First Class Magistrate Court, Kozhikode',
    'Sessions Court, Kozhikode',
    'MACT, Kozhikode',
    'Consumer Disputes Redressal Commission, Kozhikode',
    'Rent Control Court, Kozhikode',
    'Labour Court, Kozhikode',
  ],
  'Kollam': [
    'District Court, Kollam',
    'Sub Court, Kollam',
    'Munsiff Court, Kollam',
    'Family Court, Kollam',
    'Chief Judicial Magistrate Court, Kollam',
    'Judicial First Class Magistrate Court, Kollam',
    'Sessions Court, Kollam',
    'MACT, Kollam',
    'Consumer Disputes Redressal Commission, Kollam',
    'Rent Control Court, Kollam',
  ],
  'Palakkad': [
    'District Court, Palakkad',
    'Sub Court, Palakkad',
    'Munsiff Court, Palakkad',
    'Family Court, Palakkad',
    'Chief Judicial Magistrate Court, Palakkad',
    'Judicial First Class Magistrate Court, Palakkad',
    'Sessions Court, Palakkad',
    'MACT, Palakkad',
    'Consumer Disputes Redressal Commission, Palakkad',
    'Rent Control Court, Palakkad',
  ],
  'Alappuzha': [
    'District Court, Alappuzha',
    'Sub Court, Alappuzha',
    'Munsiff Court, Alappuzha',
    'Family Court, Alappuzha',
    'Chief Judicial Magistrate Court, Alappuzha',
    'Judicial First Class Magistrate Court, Alappuzha',
    'Sessions Court, Alappuzha',
    'MACT, Alappuzha',
    'Consumer Disputes Redressal Commission, Alappuzha',
  ],
  'Kottayam': [
    'District Court, Kottayam',
    'Sub Court, Kottayam',
    'Munsiff Court, Kottayam',
    'Family Court, Kottayam',
    'Chief Judicial Magistrate Court, Kottayam',
    'Judicial First Class Magistrate Court, Kottayam',
    'Sessions Court, Kottayam',
    'MACT, Kottayam',
    'Consumer Disputes Redressal Commission, Kottayam',
    'Rent Control Court, Kottayam',
  ],
  'Idukki': [
    'District Court, Idukki',
    'Sub Court, Idukki',
    'Munsiff Court, Idukki',
    'Chief Judicial Magistrate Court, Idukki',
    'Judicial First Class Magistrate Court, Idukki',
    'Sessions Court, Idukki',
    'MACT, Idukki',
    'Consumer Disputes Redressal Commission, Idukki',
  ],
  'Pathanamthitta': [
    'District Court, Pathanamthitta',
    'Sub Court, Pathanamthitta',
    'Munsiff Court, Pathanamthitta',
    'Family Court, Pathanamthitta',
    'Chief Judicial Magistrate Court, Pathanamthitta',
    'Judicial First Class Magistrate Court, Pathanamthitta',
    'Sessions Court, Pathanamthitta',
    'MACT, Pathanamthitta',
    'Consumer Disputes Redressal Commission, Pathanamthitta',
  ],
  'Malappuram': [
    'District Court, Malappuram',
    'Sub Court, Malappuram',
    'Munsiff Court, Malappuram',
    'Family Court, Malappuram',
    'Chief Judicial Magistrate Court, Malappuram',
    'Judicial First Class Magistrate Court, Malappuram',
    'Sessions Court, Malappuram',
    'MACT, Malappuram',
    'Consumer Disputes Redressal Commission, Malappuram',
  ],
  'Kannur': [
    'District Court, Kannur',
    'Sub Court, Kannur',
    'Munsiff Court, Kannur',
    'Family Court, Kannur',
    'Chief Judicial Magistrate Court, Kannur',
    'Judicial First Class Magistrate Court, Kannur',
    'Sessions Court, Kannur',
    'MACT, Kannur',
    'Consumer Disputes Redressal Commission, Kannur',
    'Rent Control Court, Kannur',
  ],
  'Kasaragod': [
    'District Court, Kasaragod',
    'Sub Court, Kasaragod',
    'Munsiff Court, Kasaragod',
    'Family Court, Kasaragod',
    'Chief Judicial Magistrate Court, Kasaragod',
    'Judicial First Class Magistrate Court, Kasaragod',
    'Sessions Court, Kasaragod',
    'MACT, Kasaragod',
    'Consumer Disputes Redressal Commission, Kasaragod',
  ],
  'Wayanad': [
    'District Court, Wayanad',
    'Sub Court, Wayanad',
    'Munsiff Court, Wayanad',
    'Chief Judicial Magistrate Court, Wayanad',
    'Judicial First Class Magistrate Court, Wayanad',
    'Sessions Court, Wayanad',
    'MACT, Wayanad',
    'Consumer Disputes Redressal Commission, Wayanad',
  ],
  'Other': [
    'Other Court / Tribunal',
  ],
};
