export const KERALA_DISTRICTS = [
  'High Court of Kerala',
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasaragod',
  'Kollam',
  'Kottayam',
  'Kozhikode',
  'Malappuram',
  'Palakkad',
  'Pathanamthitta',
  'Thiruvananthapuram',
  'Thrissur',
  'Wayanad',
  'Other'
];

export const COURTS_BY_DISTRICT: Record<string, string[]> = {
  'High Court of Kerala': [
    'High Court of Kerala — Original Side',
    'High Court of Kerala — Appellate Side',
    'High Court of Kerala — Writ Jurisdiction',
  ],
  'Thiruvananthapuram': [
    "Thiruvananthapuram Vanchiyoor (City Complex): Principal District & Sessions Court",
    "Thiruvananthapuram Vanchiyoor (City Complex): Additional District & Sessions Courts (I to VIII)",
    "Thiruvananthapuram Vanchiyoor (City Complex): CBI Special Court",
    "Thiruvananthapuram Vanchiyoor (City Complex): Special Court for Prevention of Corruption Act",
    "Thiruvananthapuram Vanchiyoor (City Complex): Motor Accident Claims Tribunal (MACT)",
    "Thiruvananthapuram Vanchiyoor (City Complex): Additional MACTs",
    "Thiruvananthapuram Vanchiyoor (City Complex): Family Court",
    "Thiruvananthapuram Vanchiyoor (City Complex): Subordinate Judge's Courts (Principal & Additional)",
    "Thiruvananthapuram Vanchiyoor (City Complex): Munsiff Courts",
    "Thiruvananthapuram Vanchiyoor (City Complex): Rent Control Court",
    "Thiruvananthapuram Vanchiyoor (City Complex): Co-Operative Tribunal",
    "Thiruvananthapuram Vanchiyoor (City Complex): Local Self Government Institutions Tribunal",
    "Thiruvananthapuram Vanchiyoor (City Complex): Chief Judicial Magistrate (CJM)",
    "Thiruvananthapuram Vanchiyoor (City Complex): Additional CJM",
    "Thiruvananthapuram Vanchiyoor (City Complex): Judicial First Class Magistrate (JFCM) Courts (I to XI, Traffic)",
    "Thiruvananthapuram Vanchiyoor (City Complex): Gram Nyayalaya",
    "Neyyattinkara: Additional District Court",
    "Neyyattinkara: Sub Court",
    "Neyyattinkara: Munsiff Court",
    "Neyyattinkara: Family Court",
    "Neyyattinkara: MACT",
    "Neyyattinkara: JFCM (I & II)",
    "Nedumangad: Additional District Court",
    "Nedumangad: Sub Court",
    "Nedumangad: Munsiff Court",
    "Nedumangad: Family Court",
    "Nedumangad: MACT",
    "Nedumangad: JFCM (I & II)",
    "Attingal: Additional District Court",
    "Attingal: Sub Court",
    "Attingal: Munsiff Court",
    "Attingal: Family Court",
    "Attingal: MACT",
    "Attingal: JFCM (I & II)",
    "Varkala: Munsiff Court",
    "Varkala: JFCM",
    "Kattakkada: Munsiff Court",
    "Kattakkada: JFCM",
    "Parassala: Gram Nyayalaya",
    "Parassala: JFCM"
  ],
  'Kollam': [
    "Kollam City: Principal District & Sessions Court",
    "Kollam City: Additional District & Sessions Courts (I, II, Adhoc I-III)",
    "Kollam City: Wakf Tribunal (III Addl.)",
    "Kollam City: MACT",
    "Kollam City: Family Court",
    "Kollam City: Labour Court",
    "Kollam City: Principal & Additional Sub Courts",
    "Kollam City: Principal & Additional Munsiff Courts",
    "Kollam City: CJM",
    "Kollam City: JFCM (I, II)",
    "Kollam City: Temporary JFCM",
    "Kottarakkara: Additional Sessions Judge (Abkari)",
    "Kottarakkara: Sub Court",
    "Kottarakkara: Munsiff Court",
    "Kottarakkara: Family Court",
    "Kottarakkara: JFCM (I & II)",
    "Punalur: MACT",
    "Punalur: Munsiff Court",
    "Punalur: JFCM (I, II-Forest Offences, III)",
    "Karunagappally: Munsiff Court",
    "Karunagappally: JFCM",
    "Sasthamcotta: Munsiff-Magistrate Court",
    "Sasthamcotta: Temporary JFCM",
    "Paravur: Munsiff-Magistrate Court",
    "Paravur: Temporary JFCM",
    "Chavara: Temporary JFCM",
    "Kadakkal: Temporary JFCM"
  ],
  'Pathanamthitta': [
    "Pathanamthitta Town: Principal District & Sessions Court",
    "Pathanamthitta Town: Additional District Courts",
    "Pathanamthitta Town: Sub Court",
    "Pathanamthitta Town: Munsiff Court",
    "Pathanamthitta Town: Family Court",
    "Pathanamthitta Town: MACT",
    "Pathanamthitta Town: CJM",
    "Pathanamthitta Town: JFCM",
    "Thiruvalla: Sub Court",
    "Thiruvalla: Munsiff Court",
    "Thiruvalla: Family Court",
    "Thiruvalla: JFCM",
    "Adoor: Sub Court",
    "Adoor: Munsiff Court",
    "Adoor: Family Court",
    "Adoor: MACT",
    "Adoor: JFCM",
    "Ranni: Munsiff-Magistrate Court",
    "Ranni: Gram Nyayalaya",
    "Mallappally: Munsiff-Magistrate Court",
    "Kozhencherry: Gram Nyayalaya"
  ],
  'Alappuzha': [
    "Alappuzha Town: Principal District & Sessions Court",
    "Alappuzha Town: Additional District Courts",
    "Alappuzha Town: Sub Court",
    "Alappuzha Town: Munsiff Court",
    "Alappuzha Town: Family Court",
    "Alappuzha Town: MACT",
    "Alappuzha Town: CJM",
    "Alappuzha Town: JFCM Courts",
    "Mavelikkara: Additional District Court",
    "Mavelikkara: Sub Court",
    "Mavelikkara: Munsiff Court",
    "Mavelikkara: Family Court",
    "Mavelikkara: MACT",
    "Mavelikkara: JFCM Courts",
    "Cherthala: Sub Court",
    "Cherthala: Munsiff Court",
    "Cherthala: Family Court",
    "Cherthala: MACT",
    "Cherthala: JFCM Courts",
    "Chengannur: Munsiff Court",
    "Chengannur: JFCM",
    "Kayamkulam: Munsiff Court",
    "Kayamkulam: JFCM",
    "Haripad: Munsiff Court",
    "Haripad: JFCM",
    "Ambalappuzha: Munsiff-Magistrate Court",
    "Ramankary: Munsiff-Magistrate Court"
  ],
  'Kottayam': [
    "Kottayam City: Principal District & Sessions Court",
    "Kottayam City: Additional District Courts (I to V)",
    "Kottayam City: Vigilance Court",
    "Kottayam City: MACT",
    "Kottayam City: Sub Court",
    "Kottayam City: Munsiff Court",
    "Kottayam City: Family Court",
    "Kottayam City: CJM",
    "Kottayam City: JFCM (I, II, III)",
    "Pala: Sub Court",
    "Pala: Munsiff Court",
    "Pala: Family Court",
    "Pala: MACT",
    "Pala: JFCM",
    "Changanacherry: Munsiff Court",
    "Changanacherry: JFCM",
    "Kanjirappally (Ponkunnam): Munsiff Court",
    "Kanjirappally (Ponkunnam): JFCM (I & II)",
    "Vaikom: Munsiff Court",
    "Vaikom: JFCM",
    "Vaikom: Gram Nyayalaya",
    "Ettumanoor: Munsiff Court",
    "Ettumanoor: Family Court",
    "Ettumanoor: JFCM",
    "Erattupetta: Munsiff Court",
    "Erattupetta: JFCM",
    "Pampady: Gram Nyayalaya"
  ],
  'Idukki': [
    "Thodupuzha: Principal District & Sessions Court",
    "Thodupuzha: Sub Court",
    "Thodupuzha: Munsiff Court",
    "Thodupuzha: Family Court",
    "Thodupuzha: MACT",
    "Thodupuzha: CJM",
    "Thodupuzha: JFCM",
    "Muttom: Additional District & Sessions Courts",
    "Muttom: NDPS/Special Courts",
    "Kattappana: Sub Court",
    "Kattappana: Munsiff Court",
    "Kattappana: Family Court",
    "Kattappana: MACT",
    "Kattappana: JFCM",
    "Devikulam (Munnar): Sub Court",
    "Devikulam (Munnar): Munsiff Court",
    "Devikulam (Munnar): JFCM",
    "Peermade: Munsiff Court",
    "Peermade: JFCM (I & II)",
    "Adimaly: JFCM",
    "Nedumkandam: JFCM",
    "Idukki (Painavu): JFCM",
    "Azhutha: Gram Nyayalaya"
  ],
  'Ernakulam': [
    "Ernakulam City: High Court of Kerala",
    "Ernakulam City: Principal District & Sessions Court",
    "Ernakulam City: Additional District Courts",
    "Ernakulam City: CBI Special Courts",
    "Ernakulam City: NIA Special Court",
    "Ernakulam City: Sub Courts",
    "Ernakulam City: Munsiff Courts",
    "Ernakulam City: Family Court",
    "Ernakulam City: MACT",
    "Ernakulam City: CJM",
    "Ernakulam City: Additional CJM (Economic Offences)",
    "Ernakulam City: Additional CJM (MP/MLA)",
    "Ernakulam City: JFCM (1, 2, 8, 9)",
    "Kochi / Mattancherry: Sub Court",
    "Kochi / Mattancherry: Munsiff Court",
    "Kochi / Mattancherry: JFCM (1, 2, Mattancherry)",
    "North Paravur: Additional District Court",
    "North Paravur: Sub Court",
    "North Paravur: Munsiff Court",
    "North Paravur: MACT",
    "North Paravur: JFCM (1, 3)",
    "North Paravur: Gram Nyayalaya",
    "Muvattupuzha: Additional District Court",
    "Muvattupuzha: Sub Court",
    "Muvattupuzha: Munsiff Court",
    "Muvattupuzha: Family Court",
    "Muvattupuzha: MACT",
    "Muvattupuzha: JFCM (1, 3)",
    "Aluva: Sub Court",
    "Aluva: Munsiff Court",
    "Aluva: JFCM (1, 2)",
    "Perumbavoor: Sub Court",
    "Perumbavoor: Munsiff Court",
    "Perumbavoor: JFCM (1, 3, 4)",
    "Kothamangalam: Munsiff Court",
    "Kothamangalam: JFCM (1, 2)",
    "Angamaly: Munsiff Court",
    "Angamaly: JFCM",
    "Thripunithura: Munsiff Court",
    "Thripunithura: JFCM",
    "Kakkanad: Standalone JFCM Court",
    "Kalamassery: Standalone JFCM Court",
    "Njarakkal: Standalone JFCM Court",
    "Chottanikkara: Standalone JFCM Court",
    "Kolenchery: Standalone JFCM Court",
    "Piravom: Standalone JFCM Court",
    "Vadavucode: Gram Nyayalaya"
  ],
  'Thrissur': [
    "Thrissur City: Principal District & Sessions Court",
    "Thrissur City: Additional District Courts",
    "Thrissur City: Vigilance Court",
    "Thrissur City: Sub Courts",
    "Thrissur City: Munsiff Courts",
    "Thrissur City: Family Court",
    "Thrissur City: MACT",
    "Thrissur City: CJM",
    "Thrissur City: Additional CJM",
    "Thrissur City: JFCM (1, 2, 3)",
    "Irinjalakuda: Additional District Court",
    "Irinjalakuda: Sub Court",
    "Irinjalakuda: Munsiff Court",
    "Irinjalakuda: Family Court",
    "Irinjalakuda: MACT",
    "Irinjalakuda: JFCM",
    "Kunnamkulam: Sub Court",
    "Kunnamkulam: Munsiff Court",
    "Kunnamkulam: JFCM",
    "Chalakudy: Munsiff Court",
    "Chalakudy: JFCM",
    "Wadakkanchery: Munsiff Court",
    "Wadakkanchery: JFCM",
    "Chavakkad: Munsiff Court",
    "Chavakkad: JFCM",
    "Kodungallur: Munsiff Court",
    "Kodungallur: JFCM"
  ],
  'Palakkad': [
    "Palakkad Town: Principal District & Sessions Court",
    "Palakkad Town: Additional District Courts",
    "Palakkad Town: Sub Courts",
    "Palakkad Town: Munsiff Courts",
    "Palakkad Town: Family Court",
    "Palakkad Town: MACT",
    "Palakkad Town: CJM",
    "Palakkad Town: JFCM Courts",
    "Ottapalam: Additional District Court",
    "Ottapalam: Sub Court",
    "Ottapalam: Munsiff Court",
    "Ottapalam: Family Court",
    "Ottapalam: MACT",
    "Ottapalam: JFCM",
    "Mannarkkad: SC/ST Special Court",
    "Mannarkkad: Sub Court",
    "Mannarkkad: Munsiff Court",
    "Mannarkkad: JFCM",
    "Chittur: Munsiff Court",
    "Chittur: JFCM",
    "Alathur: Munsiff Court",
    "Alathur: JFCM",
    "Pattambi: Munsiff Court",
    "Pattambi: JFCM",
    "Shornur: JFCM"
  ],
  'Malappuram': [
    "Manjeri: Principal District & Sessions Court",
    "Manjeri: Additional District Courts",
    "Manjeri: Sub Court",
    "Manjeri: Munsiff Court",
    "Manjeri: MACT",
    "Manjeri: SC/ST Special Court",
    "Manjeri: CJM",
    "Manjeri: JFCM (I & II)",
    "Tirur: Additional District Court",
    "Tirur: Sub Court",
    "Tirur: Munsiff Court",
    "Tirur: Family Court",
    "Tirur: MACT",
    "Tirur: Fast Track Special Court (FTSC)",
    "Tirur: JFCM (I)",
    "Perinthalmanna: Munsiff-Magistrate Court",
    "Perinthalmanna: FTSC (I & II)",
    "Perinthalmanna: JFCM (I & II)",
    "Malappuram Town: Family Court",
    "Malappuram Town: JFCM",
    "Parappanagadi: Munsiff Court",
    "Parappanagadi: FTSC",
    "Parappanagadi: JFCM (I)",
    "Ponnani: Munsiff-Magistrate Court",
    "Ponnani: FTSC",
    "Ponnani: JFCM",
    "Nilambur: Munsiff-Magistrate Court",
    "Nilambur: FTSC",
    "Nilambur: JFCM",
    "Edappal: Gram Nyayalayas",
    "Pulamanthole: Gram Nyayalayas"
  ],
  'Kozhikode': [
    "Kozhikode City: Principal District & Sessions Court",
    "Kozhikode City: Additional District Courts",
    "Kozhikode City: Special Courts",
    "Kozhikode City: Sub Courts",
    "Kozhikode City: Munsiff Courts",
    "Kozhikode City: Family Court",
    "Kozhikode City: MACT",
    "Kozhikode City: CJM",
    "Kozhikode City: JFCM Courts",
    "Vadakara: Additional District Court",
    "Vadakara: Sub Court",
    "Vadakara: Munsiff Court",
    "Vadakara: Family Court",
    "Vadakara: MACT",
    "Vadakara: JFCM",
    "Koyilandy: Sub Court",
    "Koyilandy: Munsiff Court",
    "Koyilandy: MACT",
    "Koyilandy: JFCM",
    "Thamarassery: Munsiff Court",
    "Thamarassery: JFCM",
    "Nadapuram: Munsiff Court",
    "Nadapuram: JFCM",
    "Payyoli: Standalone JFCM Court",
    "Perambra: Standalone JFCM Court",
    "Kunnamangalam: Standalone JFCM Court"
  ],
  'Wayanad': [
    "Kalpetta: Principal District & Sessions Court",
    "Kalpetta: Sub Court",
    "Kalpetta: Munsiff Court",
    "Kalpetta: Family Court",
    "Kalpetta: MACT",
    "Kalpetta: CJM",
    "Kalpetta: JFCM",
    "Sulthan Bathery: Sub Court",
    "Sulthan Bathery: Munsiff Court",
    "Sulthan Bathery: Fast Track Court",
    "Sulthan Bathery: JFCM",
    "Mananthavady: Munsiff Court",
    "Mananthavady: JFCM",
    "Panamaram: Gram Nyayalaya"
  ],
  'Kannur': [
    "Thalassery: Principal District & Sessions Court",
    "Thalassery: Additional District Courts",
    "Thalassery: Sub Courts",
    "Thalassery: Munsiff Courts",
    "Thalassery: Family Court",
    "Thalassery: MACT",
    "Thalassery: CJM",
    "Thalassery: JFCM Courts",
    "Kannur Town: Additional District Court",
    "Kannur Town: Sub Court",
    "Kannur Town: Munsiff Court",
    "Kannur Town: Family Court",
    "Kannur Town: JFCM",
    "Payyanur: Sub Court",
    "Payyanur: Munsiff Court",
    "Payyanur: JFCM",
    "Taliparamba: Sub Court",
    "Taliparamba: Munsiff Court",
    "Taliparamba: JFCM",
    "Kuthuparamba: Munsiff Court",
    "Kuthuparamba: JFCM",
    "Mattannur: Munsiff Court",
    "Mattannur: JFCM",
    "Chakkarakkal: Gram Nyayalaya"
  ],
  'Kasaragod': [
    "Kasaragod Town: Principal District & Sessions Court",
    "Kasaragod Town: Additional District Courts",
    "Kasaragod Town: Sub Court",
    "Kasaragod Town: Munsiff Court",
    "Kasaragod Town: Family Court",
    "Kasaragod Town: MACT",
    "Kasaragod Town: CJM",
    "Kasaragod Town: JFCM",
    "Hosdurg (Kanhangad): Additional District Court",
    "Hosdurg (Kanhangad): Sub Court",
    "Hosdurg (Kanhangad): Munsiff Court",
    "Hosdurg (Kanhangad): Family Court",
    "Hosdurg (Kanhangad): MACT",
    "Hosdurg (Kanhangad): JFCM (I & II)",
    "Neeleswaram: JFCM / Gram Nyayalaya",
    "Badiyadka: Gram Nyayalaya"
  ],
  'Other': [
    'Other Court / Tribunal'
  ]
};
